## INITIAL DATA EXPLORATION

In [4]:
#TO DISPLAY FIRST FEW RECORDS
uber_df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,waiting time,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2025-01-12,15:44:00,UBR100294,Cancelled by Driver,CUST1016,UberXL,NaN,Melbourne,NaN,4.9,...,NaN,1,Wrong pickup location,0,NaN,0.00,12.95,2.5,NaN,Credit Card
1,2025-03-12,05:17:00,UBR100453,Completed,CUST1040,Uber Black,Los Angeles,Madrid,11.3,4.9,...,NaN,0,NaN,0,NaN,79.67,22.87,3.7,1.3,PayPal
2,2025-01-13,11:35:00,UBR100638,Completed,CUST1004,Uber Comfort,Melbourne,Dubai,3.7,18.2,...,NaN,0,NaN,0,NaN,124.67,32.51,3.1,3.6,UPI
3,2025-05-22,08:00:00,UBR100139,Cancelled by Driver,CUST1150,UberXL,Birmingham,Manchester,6.8,11.4,...,NaN,1,Too far from pickup,0,NaN,0.00,29.12,NaN,NaN,Cash
4,2025-01-20,11:30:00,UBR100804,Completed,CUST1077,Uber Green,Paris,Dubai,10.2,24.3,...,NaN,0,NaN,0,NaN,56.68,25.32,2.9,1.3,PayPal

In [5]:
#TO DISPLAY LAST FEW ROWS
uber_df.tail()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,waiting time,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
1030,2025-06-02,23:40:00,UBR100087,Completed,CUST1209,UberX,Rome,Manchester,16.1,16.5,...,NaN,0,NaN,0,NaN,68.48,19.43,1.9,1.1,Credit Card
1031,2025-01-02,14:03:00,UBR100330,Completed,CUST1120,UberXL,Madrid,Vancouver,16.8,7.7,...,NaN,0,NaN,0,NaN,25.74,10.14,2.7,1.0,Debit Card
1032,2025-02-20,03:29:00,UBR100620,Cancelled by Customer,CUST1125,Uber Comfort,Chicago,Birmingham,11.1,21.2,...,Wrong pickup location,0,NaN,0,NaN,0.00,16.04,NaN,NaN,Cash
1033,2025-06-24,20:16:00,UBR100121,Completed,CUST1054,UberXL,New York,Paris,7.4,3.4,...,NaN,0,NaN,0,NaN,37.92,9.13,2.0,4.3,Cash
1034,2025-05-20,10:05:00,UBR100860,Cancelled by Driver,CUST1219,Uber Black,New York,Rome,8.3,24.5,...,NaN,1,Personal emergency,0,NaN,0.00,33.46,1.4,NaN,Debit Card

In [6]:
#DIMENSION OF THE DATASET (NUMBER OF ROWS & NUMBER OF COLUMNS)
uber_df.shape

(1035, 21)

In [7]:
#QUICK OVERVIEW OF THE DATAFRAME
uber_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               1035 non-null   str
 1   Time                               1035 non-null   str
 2   Booking ID                         1035 non-null   str
 3   Booking Status                     1035 non-null   str
 4   Customer ID                        1014 non-null   str
 5   Vehicle Type                       1020 non-null   str
 6   Pickup Location                    1019 non-null   str
 7   Drop Location                      1020 non-null   str
 8   waiting time                       994 non-null    float64
 9   Avg CTAT                           1004 non-null   float64
 10  Cancelled Rides by Customer        1035 non-null   int64
 11  Reason for cancelling by Customer  94 non-null     str
 12  Cancelled Rides by Driver          1035 non-null   int64
 13  Driver Cancellation Reason         116 non-null    str
 14  Incomplete Rides                   1035 non-null   int64
 15  Incomplete Rides Reason            72 non-null     str
 16  Booking Value                      1007 non-null   float64
 17  Ride Distance                      1009 non-null   float64
 18  Driver Ratings                     887 non-null    float64
 19  Customer Rating                    702 non-null    float64
 20  Payment Method                     1009 non-null   str
dtypes: float64(6), int64(3), str(12)
memory usage: 169.9 KB

In [8]:
#SIZE OF DATAFRAME : TOTAL NUMBER OF ROWS AND COLUMNS
uber_df.size

21735

In [9]:
#TO DISPLAY ALL THE COLUMN NAMES PRESENT IN DATAFRAME
uber_df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'waiting time',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='str')

In [10]:
#TO RETRIVE/ DISPLAY COLUMN NAME BASED ON INDEX
uber_df.columns[10]

'Cancelled Rides by Customer'

In [11]:
# TO CONVERT DATAFRAME COLUMNS (INDEX) INTO A LIST
list(uber_df.columns)

['Date',
 'Time',
 'Booking ID',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'waiting time',
 'Avg CTAT',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method']

In [12]:
#TO DISPLAY DATATYPES OF EACH COLUMNS PRESENT IN DATAFRAME
uber_df.dtypes

Date                                     str
Time                                     str
Booking ID                               str
Booking Status                           str
Customer ID                              str
Vehicle Type                             str
Pickup Location                          str
Drop Location                            str
waiting time                         float64
Avg CTAT                             float64
Cancelled Rides by Customer            int64
Reason for cancelling by Customer        str
Cancelled Rides by Driver              int64
Driver Cancellation Reason               str
Incomplete Rides                       int64
Incomplete Rides Reason                  str
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                           str
dtype: object

In [13]:
#TO SELECT & DISPLAY PARTICULAR DATATYPE COLUMNS
uber_df.select_dtypes(include=['float64'])   #TO SELECT DATA TYPE: float64

,waiting time,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating
0,NaN,4.9,0.00,12.95,2.5,NaN
1,11.3,4.9,79.67,22.87,3.7,1.3
2,3.7,18.2,124.67,32.51,3.1,3.6
3,6.8,11.4,0.00,29.12,NaN,NaN
4,10.2,24.3,56.68,25.32,2.9,1.3
...,...,...,...,...,...,...
1030,16.1,16.5,68.48,19.43,1.9,1.1
1031,16.8,7.7,25.74,10.14,2.7,1.0
1032,11.1,21.2,0.00,16.04,NaN,NaN
1033,7.4,3.4,37.92,9.13,2.0,4.3
1034,8.3,24.5,0.00,33.46,1.4,NaN

In [14]:
#TO SELECT & DISPLAY PARTICULAR DATATYPE COLUMNS
uber_df.select_dtypes(include=['str'])   #TO SELECT DATA TYPE: str

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Reason for cancelling by Customer,Driver Cancellation Reason,Incomplete Rides Reason,Payment Method
0,2025-01-12,15:44:00,UBR100294,Cancelled by Driver,CUST1016,UberXL,NaN,Melbourne,NaN,Wrong pickup location,NaN,Credit Card
1,2025-03-12,05:17:00,UBR100453,Completed,CUST1040,Uber Black,Los Angeles,Madrid,NaN,NaN,NaN,PayPal
2,2025-01-13,11:35:00,UBR100638,Completed,CUST1004,Uber Comfort,Melbourne,Dubai,NaN,NaN,NaN,UPI
3,2025-05-22,08:00:00,UBR100139,Cancelled by Driver,CUST1150,UberXL,Birmingham,Manchester,NaN,Too far from pickup,NaN,Cash
4,2025-01-20,11:30:00,UBR100804,Completed,CUST1077,Uber Green,Paris,Dubai,NaN,NaN,NaN,PayPal
...,...,...,...,...,...,...,...,...,...,...,...,...
1030,2025-06-02,23:40:00,UBR100087,Completed,CUST1209,UberX,Rome,Manchester,NaN,NaN,NaN,Credit Card
1031,2025-01-02,14:03:00,UBR100330,Completed,CUST1120,UberXL,Madrid,Vancouver,NaN,NaN,NaN,Debit Card
1032,2025-02-20,03:29:00,UBR100620,Cancelled by Customer,CUST1125,Uber Comfort,Chicago,Birmingham,Wrong pickup location,NaN,NaN,Cash
1033,2025-06-24,20:16:00,UBR100121,Completed,CUST1054,UberXL,New York,Paris,NaN,NaN,NaN,Cash
1034,2025-05-20,10:05:00,UBR100860,Cancelled by Driver,CUST1219,Uber Black,New York,Rome,NaN,Personal emergency,NaN,Debit Card

In [15]:
#To generate a statistical summary of the data frame (five point summary for numeric columns)
uber_df.describe()

,waiting time,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,994.000000,1004.000000,1035.000000,1035.000000,1035.000000,1007.000000,1009.000000,887.000000,702.000000
mean,9.315493,13.882171,0.090821,0.112077,0.069565,40.734955,18.135114,2.892334,3.046724
std,4.962192,6.408082,0.287494,0.315614,0.254536,32.685249,9.551037,1.143333,1.143092
min,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.240000,1.000000,1.000000
25%,4.925000,8.500000,0.000000,0.000000,0.000000,12.300000,10.140000,1.900000,2.100000
50%,9.100000,13.750000,0.000000,0.000000,0.000000,37.890000,18.090000,2.900000,3.100000
75%,13.600000,19.500000,0.000000,0.000000,0.000000,61.840000,26.220000,3.800000,4.000000
max,18.000000,25.000000,1.000000,1.000000,1.000000,130.370000,34.960000,5.000000,5.000000

In [16]:
#To generate a descriptive summary for categorical columns (objects)
uber_df.describe(include='object')

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Reason for cancelling by Customer,Driver Cancellation Reason,Incomplete Rides Reason,Payment Method
count,1035,1035,1035,1035,1014,1020,1019,1020,94,116,72,1009
unique,181,722,986,4,245,5,20,20,5,5,5,6
top,2025-01-24,13:35:00,UBR100804,Completed,CUST1083,UberXL,Toronto,London,Driver taking too long,Personal emergency,Route issue,Credit Card
freq,12,5,2,753,11,221,67,63,26,27,18,187